version: '2.6'
services:
  weiyu:
    image:  MQBench:torch2.2
    container_name: MQBench_torch2.2
    shm_size: 4096M
    privileged: true
    ipc: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    environment:
      - DISPLAY=:0
    network_mode: host
    stdin_open: true
    tty: true
    restart: always